### PR TITLE
Yuechens fixes for functional bugs

### LINKED ISSUE #141: [PE-D][Tester B] Suggested command for edit does not work due to missing space
-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: howen02/ped#9

### PR DESCRIPTION
**Pull request by yuechen2001**
Fixes #141, #144, #146

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -66,7 +68,7 @@ public class EditCommand extends Command {
     private final EditContactDescriptor editContactDescriptor;
 
     /**
-     * @param index of the contact in the filtered contact list to edit
+     * @param index                 of the contact in the filtered contact list to edit
```
Comment (angsongyee) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:71]: I think this might be accidentally added?

File: src/main/java/seedu/address/ui/TeamListPanel.java [hunk 2]
```diff
@@ -26,21 +26,25 @@ public class TeamListPanel extends UiPart<Region> {
...
+    class TeamListCell extends ListCell<Team> {
+        @Override
+        protected void updateItem(Team team, boolean empty) {
+            super.updateItem(team, empty);
+
+            if (empty || team == null) {
+                setGraphic(null);
+                setText(null);
+            } else {
+                setGraphic(new TeamCard(team, getIndex() + 1).getRoot());
```
Comment (angsongyee) [inline src/main/java/seedu/address/ui/TeamListPanel.java:44]: Can we keep the previous change? `setPrefWidth(0)` needs to be called in each cell for layout reasons.

**Review by angsongyee — CHANGES_REQUESTED** [review]

**Comment by yuechen2001** [comment]
> Also missing fixes for #146

Fix for #146 is under the "[Update user guide link for help command](https://github.com/AY2324S2-CS2103T-T12-1/tp/pull/158/commits/c8ad58f34400d7740aa648617e20032760b357b4)".

What I did was replace the link to the original AB3 UG to the link for our UG

**Comment by angsongyee** [comment]
> > Also missing fixes for #146
> 
> Fix for #146 is under the "[Update user guide link for help command](https://github.com/AY2324S2-CS2103T-T12-1/tp/pull/158/commits/c8ad58f34400d7740aa648617e20032760b357b4)".
> 
> What I did was replace the link to the original AB3 UG to the link for our UG

The file doesn't show up in the changed files tab for some reason...

**Review by angsongyee — APPROVED** [review]
